server:
  port: 8082
spring:
  application:
    name: service-b
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info
    org.springframework.cloud: debug
    org.springframework.cloud.config.client: debug
    org.springframework.web: debug
    org.springframework.boot: debug