spring:
  application:
    name: auth-server
  banner:
    location: classpath:banner.txt
  cache:
    type: caffeine
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: false
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    root: off
    org:
      springframework: info
      hibernate: info
      apache:
        commons: info
    com:
        twigcodes: debug
