spring:
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:sql/h2
        clean-disabled: false
        clean-on-validation-error: true
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: none
    h2:
        console:
            enabled: true
            path: /h2-console
