networks:
  fxr:
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    command:
    - start-dev
    - --import-realm
    - --optimized
    container_name: keycloak
    ports:
    - 9999:8080
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
#      - JAVA_OPTS_KC_HEAP="-XX:MaxHeapFreeRatio=30 -XX:MaxRAMPercentage=65"
    volumes:
    - ./themes:/opt/keycloak/themes
    - ./realms:/opt/keycloak/realms
    - ./import:/opt/keycloak/data/import
    restart: always
    networks:
    - fxr

