spring:
    application:
        name: gateway
    cloud:
      gateway:
        routes:
          - id: service-a
            uri: lb://service-a
            predicates:
              - Path=/service-a/**
            filters:
              - StripPrefix=1
          - id: service-b
            uri: lb://service-b
            predicates:
              - Path=/service-b/**
            filters:
              - StripPrefix=1

server:
  address: 0.0.0.0
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS