server:
  port: 8800
spring:
  application:
    name: cms
  banner:
    location: classpath:banner.txt
  data:
    mongodb:
      uri: mongodb://localhost:27017/fxr_cms
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
