server:
  port: 8081
spring:
  application:
    name: service-a
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:9999/auth/realms/fangxiaoer/protocol/openid-connect/certs}  #<1>
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

logging:
  level:
    root: info
    org.springframework.cloud: debug
    org.springframework.cloud.config.client: debug
    org.springframework.web: debug
    org.springframework.boot: debug
