server:
  port: 8999
spring:
  application:
    name: apidocs
  banner:
    location: classpath:banner.txt
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
