services:
    redis:
        image: redis:4
        container_name: redis
        ports:
        - "6379:6379"
        networks:
        - auth-server
        volumes:
        - redis-data:/data
        command: redis-server --appendonly yes
        restart: always

volumes:
    redis-data:
        driver: local

networks:
    auth-server:
        driver: bridge