server:
  port: 8888

management:
  endpoint:
    env:
      post:
        enabled: true
logging:
  level:
    com.netflix.discovery: "OFF"
    org.springframework.cloud: "DEBUG"

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/peng.wong/service-configurations.git
          basedir: spring_cloud_multi_modules